package f.s.frobot.dao;

import f.s.frobot.model.CallTask;
import f.s.frobot.model.CallTaskExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CallTaskMapper {
    long countByExample(CallTaskExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(CallTask record);

    int insertSelective(CallTask record);

    List<CallTask> selectByExample(CallTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_task
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<CallTask> selectByExampleSelective(@Param("example") CallTaskExample example, @Param("selective") CallTask.Column... selective);

    CallTask selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_task
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CallTask selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CallTask.Column... selective);

    int updateByExampleSelective(@Param("record") CallTask record, @Param("example") CallTaskExample example);

    int updateByExample(@Param("record") CallTask record, @Param("example") CallTaskExample example);

    int updateByPrimaryKeySelective(CallTask record);

    int updateByPrimaryKey(CallTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_task
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CallTask selectOneByExample(CallTaskExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_task
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CallTask selectOneByExampleSelective(@Param("example") CallTaskExample example, @Param("selective") CallTask.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_task
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<CallTask> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_task
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<CallTask> list, @Param("selective") CallTask.Column... selective);
}