package f.s.frobot.dao;

import f.s.frobot.model.CallInstance;
import f.s.frobot.model.CallInstanceExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CallInstanceMapper {
    long countByExample(CallInstanceExample example);

    int deleteByPrimaryKey(Long id);

    int insert(CallInstance record);

    int insertSelective(CallInstance record);

    List<CallInstance> selectByExample(CallInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_instance
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<CallInstance> selectByExampleSelective(@Param("example") CallInstanceExample example, @Param("selective") CallInstance.Column... selective);

    CallInstance selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_instance
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CallInstance selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") CallInstance.Column... selective);

    int updateByExampleSelective(@Param("record") CallInstance record, @Param("example") CallInstanceExample example);

    int updateByExample(@Param("record") CallInstance record, @Param("example") CallInstanceExample example);

    int updateByPrimaryKeySelective(CallInstance record);

    int updateByPrimaryKey(CallInstance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_instance
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CallInstance selectOneByExample(CallInstanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_instance
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CallInstance selectOneByExampleSelective(@Param("example") CallInstanceExample example, @Param("selective") CallInstance.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_instance
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<CallInstance> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_instance
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<CallInstance> list, @Param("selective") CallInstance.Column... selective);
}