package f.s.frobot.dao;

import f.s.frobot.model.CallLog;
import f.s.frobot.model.CallLogExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CallLogMapper {
    long countByExample(CallLogExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(CallLog record);

    int insertSelective(CallLog record);

    List<CallLog> selectByExample(CallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<CallLog> selectByExampleSelective(@Param("example") CallLogExample example, @Param("selective") CallLog.Column... selective);

    CallLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CallLog selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CallLog.Column... selective);

    int updateByExampleSelective(@Param("record") CallLog record, @Param("example") CallLogExample example);

    int updateByExample(@Param("record") CallLog record, @Param("example") CallLogExample example);

    int updateByPrimaryKeySelective(CallLog record);

    int updateByPrimaryKey(CallLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CallLog selectOneByExample(CallLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CallLog selectOneByExampleSelective(@Param("example") CallLogExample example, @Param("selective") CallLog.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<CallLog> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_log
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<CallLog> list, @Param("selective") CallLog.Column... selective);
}