package f.s.frobot.dao;

import f.s.frobot.model.CallKyOrder;
import f.s.frobot.model.CallKyOrderExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CallKyOrderMapper {
    long countByExample(CallKyOrderExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(CallKyOrder record);

    int insertSelective(CallKyOrder record);

    List<CallKyOrder> selectByExample(CallKyOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_ky_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<CallKyOrder> selectByExampleSelective(@Param("example") CallKyOrderExample example, @Param("selective") CallKyOrder.Column... selective);

    CallKyOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_ky_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CallKyOrder selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CallKyOrder.Column... selective);

    int updateByExampleSelective(@Param("record") CallKyOrder record, @Param("example") CallKyOrderExample example);

    int updateByExample(@Param("record") CallKyOrder record, @Param("example") CallKyOrderExample example);

    int updateByPrimaryKeySelective(CallKyOrder record);

    int updateByPrimaryKey(CallKyOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_ky_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CallKyOrder selectOneByExample(CallKyOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_ky_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CallKyOrder selectOneByExampleSelective(@Param("example") CallKyOrderExample example, @Param("selective") CallKyOrder.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_ky_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<CallKyOrder> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_ky_order
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<CallKyOrder> list, @Param("selective") CallKyOrder.Column... selective);
}