package f.s.frobot.dao;

import f.s.frobot.model.CallThirdConfig;
import f.s.frobot.model.CallThirdConfigExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CallThirdConfigMapper {
    long countByExample(CallThirdConfigExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(CallThirdConfig record);

    int insertSelective(CallThirdConfig record);

    List<CallThirdConfig> selectByExample(CallThirdConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_third_config
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<CallThirdConfig> selectByExampleSelective(@Param("example") CallThirdConfigExample example,
                                                   @Param("selective") CallThirdConfig.Column... selective);

    CallThirdConfig selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_third_config
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CallThirdConfig selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") CallThirdConfig.Column... selective);

    int updateByExampleSelective(@Param("record") CallThirdConfig record, @Param("example") CallThirdConfigExample example);

    int updateByExample(@Param("record") CallThirdConfig record, @Param("example") CallThirdConfigExample example);

    int updateByPrimaryKeySelective(CallThirdConfig record);

    int updateByPrimaryKey(CallThirdConfig record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_third_config
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CallThirdConfig selectOneByExample(CallThirdConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_third_config
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    CallThirdConfig selectOneByExampleSelective(@Param("example") CallThirdConfigExample example, @Param("selective") CallThirdConfig.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_third_config
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<CallThirdConfig> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table call_third_config
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<CallThirdConfig> list, @Param("selective") CallThirdConfig.Column... selective);
}