package f.s.frobot.dao;

import f.s.frobot.model.RobotCategoryRelation;
import f.s.frobot.model.RobotCategoryRelationExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface RobotCategoryRelationMapper {
    long countByExample(RobotCategoryRelationExample example);

    int deleteByPrimaryKey(Integer id);

    int insert(RobotCategoryRelation record);

    int insertSelective(RobotCategoryRelation record);

    List<RobotCategoryRelation> selectByExample(RobotCategoryRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_category_relation
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<RobotCategoryRelation> selectByExampleSelective(@Param("example") RobotCategoryRelationExample example,
                                                         @Param("selective") RobotCategoryRelation.Column... selective);

    RobotCategoryRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_category_relation
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    RobotCategoryRelation selectByPrimaryKeySelective(@Param("id") Integer id, @Param("selective") RobotCategoryRelation.Column... selective);

    int updateByExampleSelective(@Param("record") RobotCategoryRelation record, @Param("example") RobotCategoryRelationExample example);

    int updateByExample(@Param("record") RobotCategoryRelation record, @Param("example") RobotCategoryRelationExample example);

    int updateByPrimaryKeySelective(RobotCategoryRelation record);

    int updateByPrimaryKey(RobotCategoryRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_category_relation
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    RobotCategoryRelation selectOneByExample(RobotCategoryRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_category_relation
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    RobotCategoryRelation selectOneByExampleSelective(@Param("example") RobotCategoryRelationExample example, @Param("selective") RobotCategoryRelation.Column... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_category_relation
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<RobotCategoryRelation> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table robot_category_relation
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<RobotCategoryRelation> list, @Param("selective") RobotCategoryRelation.Column... selective);
}